POST  http://localhost:3000/user
content-type: application/json

{
    "name": "bdhdh",
    "phone": "555555",
    "email": "sdsds",
    "password": "123456",
    "cpf": "sdsdsds"
}

###
GET   http://localhost:3000/user
content-type: application/json
 